<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Employee;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            [
                'name' => 'Umar Sjaifudin M.Si',
                'email' => 'umars@bps.go.id',
                'password' => 'kepalabps',
                'nip' => '197012161997031005',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1970-12-16',
                'team_id' => 6,
            ],
            [
                'name' => 'Ir. Dwi Handayani Prasetyawati M.AP',
                'email' => 'dwi@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '196810281994012001',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1968-10-28',
                'team_id' => 4,
            ],
            [
                'name' => 'Ir. Wahyu Furqandari M.M',
                'email' => 'wahyu@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '196901181994012001',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1969-01-18',
                'team_id' => 6,
            ],
            [
                'name' => 'Tasmilah SST, M.E',
                'email' => 'tasmilah@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '198309102006022001',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1983-09-10',
                'team_id' => 5,
            ],
            [
                'name' => 'Ir. Agustina Martha M.M',
                'email' => 'agustina@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '196808231994012001',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1968-08-23',
                'team_id' => 3,
            ],
            [
                'name' => 'Ahmad Junaedi S.Si, M.M',
                'email' => 'junaedi@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '197501311994011001',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1975-01-31',
                'team_id' => 3,
            ],
            [
                'name' => 'Anggi Fatwa Mauliza A.Md.Kb.N',
                'email' => 'anggi@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '200006272022012005',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2000-06-27',
                'team_id' => 1,
            ],
            [
                'name' => 'Arini Ismiati S.ST',
                'email' => 'arini@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '197912202003122006',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1979-12-20',
                'team_id' => 1,
            ],
            [
                'name' => 'Baqtiar Arifin S.Stat., MM',
                'email' => 'baqtiar@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '197806272005021002',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1978-06-27',
                'team_id' => 1,
            ],
            [
                'name' => 'Bima Sakti Krisdianto SST',
                'email' => 'bima@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '199511062017011001',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1995-11-06',
                'team_id' => 6,
            ],
            [
                'name' => 'Eka Arifianto A.Md. Lib',
                'email' => 'eka@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '199709202023211005',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1997-09-20',
                'team_id' => 6,
            ],
            [
                'name' => 'Erlisa Cantika Herawati S.Si',
                'email' => 'erlisa@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '199408052019032003',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1994-08-05',
                'team_id' => 4,
            ],
            [
                'name' => 'Ir. Ernawaty M.M',
                'email' => 'ernawaty@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '196701091992032001',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1967-01-09',
                'team_id' => 2,
            ],
            [
                'name' => 'Heru Kartiko SST',
                'email' => 'heru@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '197604211999031003',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1976-04-21',
                'team_id' => 6,
            ],
            [
                'name' => 'Rachmad Widi Wijayanto',
                'email' => 'rachmad@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '197704042006041016',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1977-04-04',
                'team_id' => 1,
            ],
            [
                'name' => 'Ratri Adhipradani Ratih S.Si',
                'email' => 'ratri@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '198510022009022012',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1985-10-02',
                'team_id' => 3,
            ],
            [
                'name' => 'Rendra Anandhika A.Md',
                'email' => 'rendra@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '198802292011011005',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1988-02-29',
                'team_id' => 6,
            ],
            [
                'name' => 'Rhyke Chrisdiana Novita S.E',
                'email' => 'rhyke@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '198404122005022001',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1984-04-12',
                'team_id' => 3,
            ],
            [
                'name' => 'Rizky Maulidya SST, M.AP',
                'email' => 'maulidya@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '199109302014102001',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1991-09-30',
                'team_id' => 5,
            ],
            [
                'name' => 'Saras Wati Utami S.Si, M.E',
                'email' => 'saras@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '198803302010122002',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1988-03-30',
                'team_id' => 4,
            ],
            [
                'name' => 'Saruni Gincahyo SE',
                'email' => 'saruni@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '196802281989031003',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1968-02-28',
                'team_id' => 3,
            ],
            [
                'name' => 'Satria Candra Wibawa A.Md',
                'email' => 'satria@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '198810282011011004',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1988-10-28',
                'team_id' => 6,
            ],
            [
                'name' => 'Siti Barokatun Solihah SST',
                'email' => 'siti@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '199110232016022001',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1999-11-02',
                'team_id' => 2,
            ],
            [
                'name' => 'Soekesi Irawati S.Psi., M.M',
                'email' => 'soekesi@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '197009251994012001',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1970-09-25',
                'team_id' => 4,
            ],
            [
                'name' => 'Windi Wijayanti S.Si, M.E',
                'email' => 'windi@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '198712182011012022',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1987-12-18',
                'team_id' => 2,
            ],
            [
                'name' => 'Yenita Mirawanti SST., M.Si',
                'email' => 'yenita@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '197806032000122002',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1978-06-03',
                'team_id' => 2,
            ],
            [
                'name' => 'Yusuf Fatoni SE',
                'email' => 'yusuf@bps.go.id',
                'password' => 'bpsmalang',
                'nip' => '197012251997031004',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1970-12-25',
                'team_id' => 4,
            ],
        ];


        foreach ($employees as $data) {
            $user = User::create([
                'name' => $data['name'],
                'email' => $data['email'],
                'password' => bcrypt($data['password']),
            ]);

            Employee::create([
                'name' => $data['name'],
                'nip' => $data['nip'],
                'jenis_kelamin' => $data['jenis_kelamin'],
                'tanggal_lahir' => $data['tanggal_lahir'],
                'team_id' => $data['team_id'],
                'user_id' => $user->id,
            ]);
        }
    }
}
